apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: php-poc-prod
type: Opaque
stringData:
  DB_HOST: "caltrans-eks-php-prod-mysql.cf26y8cg07cy.us-west-2.rds.amazonaws.com"
  DB_NAME: "appdb"
  DB_USER: "appuser"
  DB_PASS: "ChangeMe_StrongPassword_123!"
