apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: php-poc
type: Opaque
stringData:
  DB_HOST: "caltrans-eks-php-mysql.cb0uaoqys5dh.us-west-1.rds.amazonaws.com"
  DB_NAME: "appdb"
  DB_USER: "appuser"
  DB_PASS: "ChangeMe_StrongPassword_123!"
