apiVersion: v1
kind: Service
metadata:
  name: office-locator-prod-svc
  namespace: php-poc-prod
spec:
  type: LoadBalancer
  selector:
    app: office-locator-prod
  ports:
    - port: 80
      targetPort: 80
